name: Windows LiteManager RDP Setup

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'LiteManager password (min 8 chars)'
        required: true
        type: string

jobs:
  setup-rdp:
    name: Setup Windows RDP with LiteManager
    runs-on: windows-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set execution policy
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072

    - name: Install Chocolatey (if needed)
      shell: powershell
      run: |
        if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          refreshenv
        }

    - name: Install LiteManager via Chocolatey
      shell: powershell
      run: |
        choco install litemanager -y --force
        if (-not (Test-Path "$env:ProgramFiles\LiteManager\LiteManager.exe")) {
          Write-Error "LiteManager installation failed"
          exit 1
        }

    - name: Configure LiteManager
      shell: powershell
      run: |
        # Set password (from workflow input)
        $password = "${{ github.event.inputs.password }}"
        if ($password.Length -lt 8) {
          Write-Error "Password must be at least 8 characters"
          exit 1
        }

        # Configure LiteManager
        & "$env:ProgramFiles\LiteManager\LMSetup.exe" /silent /install /password:$password /accepteula
        Start-Service -Name "LiteManager Server"

    - name: Configure Windows Firewall
      shell: powershell
      run: |
        New-NetFirewallRule -DisplayName "LiteManager" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 5650,5651 -Enabled True

    - name: Get Connection Information
      shell: powershell
      run: |
        $ip = (Test-Connection -ComputerName (hostname) -Count 1).IPV4Address.IPAddressToString
        Write-Output "LiteManager connection details:"
        Write-Output "IP: $ip"
        Write-Output "Port: 5650"
        Write-Output "Password: ${{ github.event.inputs.password }}"
        Write-Output "Client download: https://litemanager.ru/en/download"

    - name: Keep runner active
      shell: powershell
      run: |
        Write-Output "RDP session will remain active for 60 minutes"
        $endTime = (Get-Date).AddMinutes(60)
        while ((Get-Date) -lt $endTime) {
          Start-Sleep -Seconds 30
          Write-Output "Session active - Time remaining: $($endTime - (Get-Date))"
        }
